import { JackpotUser, User } from "../types";

export const demoUsersInfo: User[] = [
  {
    rank: 1,
    username: "user1",
    avatar: "/src/assets/images/users/avatar1.png",
    bets: 10,
    wins: 4,
    winRate: 10 > 0 ? 4 / 10 : 0,
    topSteak: 7,
    roi: 0.62,
    netProfit: 111.45,
    depositedAmount: 9889,
    walletAddress: "EkdpMcVJ37Tnfa6jfdqdVNjsNhFMsn3tJEk12u48xFdF",
  },
  {
    rank: 2,
    username: "user2",
    avatar: "/src/assets/images/users/avatar1.png",
    bets: 5,
    wins: 3,
    winRate: 5 > 0 ? 3 / 5 : 0,
    topSteak: 5,
    roi: 0.50,
    netProfit: 100.00,
    depositedAmount: 200,
    walletAddress: "EkdpMcVJ37Tnfa6jfdqdVNjsNhFMsn3tJEk12u48xFdF",
  },
  {
    rank: 3,
    username: "user3",
    avatar: "/src/assets/images/users/avatar1.png",
    bets: 2,
    wins: 1,
    winRate: 2 > 0 ? 1 / 2 : 0,
    topSteak: 6,
    roi: 0.36,
    netProfit: 90.00,
    depositedAmount: 200,
    walletAddress: "EkdpMcVJ37Tnfa6jfdqdVNjsNhFMsn3tJEk12u48xFdF",
  },
  {
    rank: 4,
    username: "user4",
    avatar: "/src/assets/images/users/avatar1.png",
    bets: 3,
    wins: 1,
    winRate: 3 > 0 ? 1 / 3 : 0,
    topSteak: 4,
    roi: 0.45,
    netProfit: 80.00,
    depositedAmount: 200,
    walletAddress: "EkdpMcVJ37Tnfa6jfdqdVNjsNhFMsn3tJEk12u48xFdF",
  },
  {
    rank: 5,
    username: "user5",
    avatar: "/src/assets/images/users/avatar1.png",
    bets: 4,
    wins: 3,
    winRate: 4 > 0 ? 3 / 4 : 0,
    topSteak: 5,
    roi: 0.25,
    netProfit: 70.00,
     depositedAmount: 200,
    walletAddress: "EkdpMcVJ37Tnfa6jfdqdVNjsNhFMsn3tJEk12u48xFdF",
  },
];
export const jackpotDemoUsers: JackpotUser[] = [
  {
    id: 5,
    reward: 800,
    investors: [
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
    ],
  },
  // {
  //   id: 4,
  //   reward: 500,
  //   investors: [
  //     { avatar: "/src/assets/images/users/avatar1.png" },
  //     { avatar: "/src/assets/images/users/avatar1.png" },
  //     { avatar: "/src/assets/images/users/avatar1.png" },
  //     { avatar: "/src/assets/images/users/avatar1.png" },
  //     { avatar: "/src/assets/images/users/avatar1.png" },
  //     { avatar: "/src/assets/images/users/avatar1.png" },
  //     { avatar: "/src/assets/images/users/avatar1.png" },
  //   ],
  // },
  {
    id: 3,
    reward: 0,
    investors: [],
  },
  {
    id: 2,
    reward: 200,
    investors: [
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
    ],
  },
  {
    id: 1,
    reward: 100,
    investors: [
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
      { avatar: "/src/assets/images/users/avatar1.png" },
    ],
  },
];
